# Generated by Django 6.0 on 2025-12-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_compound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
