# Generated by Django 6.0 on 2026-01-01 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_compound', '0002_alter_project_description_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(max_length=150)),
                ('mw', models.FloatField(blank=True, null=True)),
                ('logD', models.FloatField(blank=True, null=True)),
                ('logP', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='project_compound.project')),
            ],
        ),
    ]
